name: Rust Build and Release

on:
  push:
    branches:
      - main
  tags:
    - v*

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        release-extension: ["", ".exe"]
    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Release Binary
        run: cargo build --release --target ${{ matrix.os }} --bin srt_translator
        env:
          CARGO_TERM_COLOR: always

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./target/${{ matrix.os }}/release/srt_translator${{ matrix.release-extension }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
